(()=>{"use strict";
const W=1000,H=560,$=s=>document.querySelector(s);
const scene=$('#scene'),bg=$('#bg'),props=$('#props'),player=$('#player'),shadow=$('#shadow'),carry=$('#carry');
const hudInfo=$('#hudInfo'),area=$('#area'),objective=$('#objective'),hint=$('#hint'),toastBox=$('#toast');
const dialogue=$('#dialogue'),portrait=$('#portrait'),speaker=$('#speaker'),text=$('#text'),choices=$('#choices');
const bag=$('#bag'),bagGrid=$('#bagGrid'),bagMsg=$('#bagMsg'),itemMenu=$('#itemMenu'),flash=$('#flash'),ending=$('#ending'),transition=$('#transition'),bgm=$('#bgm');
const A={girl:'assets/player-girl.png',boy:'assets/player-boy.png',child:'assets/npc-child.png',grandma:'assets/npc-grandma.png',boss:'assets/npc-boss.png',elephant:'assets/npc-elephant.png',belt:'assets/item-belt.png',bag:'assets/item-bag.png',photo:'assets/item-photo.png',coin:'assets/item-coin.png'};
const items={belt:{name:'매듭진 흰띠',img:A.belt,desc:'어떤 결의가 느껴진다.'},bag:{name:'큰 가방',img:A.bag,desc:'사람도 들어갈 것만 같다.'},photo:{name:'사진',img:A.photo,desc:'뒷모습이 낯익다.'},coin:{name:'코인',img:A.coin,desc:'그런데 여기서도 돈이 필요할까?'},bag_man:{name:'남자가 들어간 가방',img:A.bag,desc:'가방 안에서 작은 숨소리가 들린다.'}};
const portraits={초여름:A.girl,박이상:A.boy,여자:A.girl,남자:A.boy,꼬마:A.child,할머니:A.grandma,부장님:A.boss,코끼리:A.elephant,'':A.girl};
const doors=[{id:1,x:137,y:375,name:'꼬마의 집',room:'dojo'},{id:2,x:419,y:383,name:'할머니의 집',room:'kitchen'},{id:3,x:298,y:204,name:'부장님의 집',room:'office'},{id:4,x:578,y:198,name:'코끼리의 집',room:'memory'},{id:5,x:841,y:224,name:'마지막 성',room:'castle'}];
let S,keys={up:false,down:false,left:false,right:false,a:false,b:false},started=false,locked=false,last=performance.now(),dq=[],done=null,ci=0,bagMode='view',toastTimer,comboTimer=null;
const fresh=()=>({scene:'world',x:500,y:515,face:'left',complete:[false,false,false,false],inv:[],discarded:[],dropped:{dojo:[],kitchen:[],office:[],memory:[],castle:[]},dropSeq:0,bagHasMan:false,finalRun:false,finalPocketSeen:false,endingReady:false,q1:{pieces:new Set(),attempts:0,grown:false},q2:{dishes:new Set(),placed:new Set()},q3:{papers:0,stamp:true,holdingStamp:false},q4:{intro:false,hugged:false},q5:{attempts:0}});
function ensureBgm(){if(!bgm)return;bgm.loop=true;bgm.volume=.42;const p=bgm.play();if(p&&typeof p.catch==='function')p.catch(()=>{});}
function reset(show=true){S=fresh();locked=false;closeDialogue(true);closeBag(true);ending.className='hidden';ending.querySelector('p').textContent='THE END';$('#again').textContent='게임 다시하기';flash.className='hidden';carry.classList.add('hidden');player.src=A.girl;renderWorld();updatePlayer();$('#title').classList.add('hidden');$('#intro').classList.toggle('hidden',!show);started=!show;}
function prop(cls,x,y,html=''){const e=document.createElement('div');e.className=cls;if(!(x===0&&y===0)){e.style.left=x/W*100+'%';e.style.top=y/H*100+'%'}e.innerHTML=html;props.appendChild(e);return e;}
function npc(src,x,y,w,cls=''){const e=document.createElement('img');e.src=src;e.className='npc '+cls;e.style.left=x/W*100+'%';e.style.top=y/H*100+'%';e.style.width=w+'%';e.draggable=false;props.appendChild(e);return e;}
function base(name,cls,x=500,y=500){S.scene=name;S.x=x;S.y=y;scene.className='';scene.style.backgroundImage='none';bg.className=cls;props.innerHTML='';carry.className='hidden';hudInfo.classList.add('hidden');updatePlayer();}
function unlocked(id){if(id===1)return true;if(id<=4)return S.complete.slice(0,id-1).every(Boolean);return S.complete.every(Boolean)}
function renderWorld(){S.scene='world';scene.className='world';scene.style.backgroundImage="url('assets/world-map.png')";bg.className='';props.innerHTML='';hudInfo.classList.remove('hidden');area.textContent='기억의 마을';objective.textContent=S.complete.every(Boolean)?'성으로 향하세요.':'열린 길을 따라가세요.';doors.forEach(d=>{let ok=unlocked(d.id),fin=d.id<=4&&S.complete[d.id-1],showName=fin||(d.id===5&&ok),m=prop('marker '+(!ok?'lock ':'')+(fin?'done':''),d.x,d.y-32);m.innerHTML=`<b>${fin?'✓':ok?d.id:'🔒'}</b>${showName?`<span>${d.name}</span>`:''}`});if(S.finalRun)carry.classList.remove('hidden');updatePlayer();}
function enter(d){if(!unlocked(d.id)){toast('문은 아직 열리지 않는다.');return}if(d.id<=4&&S.complete[d.id-1]){toast('조용히 닫힌 문이다.');return}({dojo:renderDojo,kitchen:renderKitchen,office:renderOffice,memory:renderMemory,castle:renderCastle})[d.room]();}
function toast(msg,ms=1500){clearTimeout(toastTimer);toastBox.textContent=msg;toastBox.classList.remove('hidden');toastTimer=setTimeout(()=>toastBox.classList.add('hidden'),ms)}
function sceneTransition(next){if(!transition){next();return}locked=true;transition.className='active';setTimeout(next,310);setTimeout(()=>{transition.className='hidden';locked=false},760)}
function say(lines,cb){dq=lines.slice();done=cb||null;ci=0;dialogue.classList.remove('hidden');showLine();}
function showLine(){if(!dq.length){closeDialogue();return}let l=dq[0];speaker.textContent=l.who||'';portrait.src=portraits[l.who||'']||A.girl;text.textContent=l.t||'';choices.innerHTML='';ci=0;if(l.opts)l.opts.forEach((o,i)=>{let b=document.createElement('button');b.className='choice'+(i===0?' selected':'');b.textContent=o.label;b.onclick=e=>{e.stopPropagation();choose(i)};choices.appendChild(b)});}
function advance(){if(dialogue.classList.contains('hidden'))return;let l=dq[0];if(l&&l.opts){choose(ci);return}dq.shift();if(dq.length)showLine();else closeDialogue();}
function choose(i){let l=dq[0],o=l&&l.opts&&l.opts[i];if(!o)return;dialogue.classList.add('hidden');dq=[];let cb=done;done=null;o.go();if(cb)cb();}
function moveChoice(dir){let l=dq[0];if(!l||!l.opts)return;ci=(ci+dir+l.opts.length)%l.opts.length;[...choices.children].forEach((e,i)=>e.classList.toggle('selected',i===ci));}
function closeDialogue(force=false){dialogue.classList.add('hidden');dq=[];let cb=done;done=null;if(cb&&!force)cb();}
function openBag(mode='view'){if(!dialogue.classList.contains('hidden'))return;bagMode=mode;renderBag();bag.classList.remove('hidden');if(S.finalRun&&!S.finalPocketSeen){S.finalPocketSeen=true;setTimeout(()=>{bagMsg.textContent='박이상: “내가 너무 무거워서 그런 것 같아...”';S.endingReady=true;renderBag();},500)}}
function closeBag(){bag.classList.add('hidden');itemMenu.classList.add('hidden');}
function renderBag(){bagGrid.innerHTML='';itemMenu.classList.add('hidden');bagMsg.textContent=S.finalRun&&S.finalPocketSeen?'박이상: “내가 너무 무거워서 그런 것 같아...”':'';if(!S.inv.length){bagGrid.innerHTML='<div class="empty">주머니가 비어 있습니다.</div>';return}S.inv.forEach(id=>{let it=items[id],c=document.createElement('article');c.className='item';let badge=id==='bag_man'?`<img class="manbadge" src="${A.boy}">`:'';c.innerHTML=`<div class="pic"><img src="${it.img}">${badge}</div><h3>${it.name}</h3><p>${it.desc}</p>`;c.onclick=()=>openItemMenu(id);bagGrid.appendChild(c)})}
function openItemMenu(id){let it=items[id];itemMenu.innerHTML=`<div class="itemMenuCard"><img src="${it.img}"><h3>${it.name}</h3><p>어떻게 할까?</p><div class="menuActions"></div><button class="cancel">취소</button></div>`;let actions=itemMenu.querySelector('.menuActions');const add=(label,fn)=>{let b=document.createElement('button');b.textContent=label;b.onclick=fn;actions.appendChild(b)};if(S.scene==='memory'&&!S.q4.hugged)add('코끼리에게 건네주기',()=>offerToElephant(id));if(bagMode==='discard'&&id!=='bag')add('쓰레기통에 버리기',()=>discard(id));else if(S.finalRun&&id==='bag_man'&&S.endingReady)add('바닥에 내려놓기',finalDrop);else add('바닥에 내려놓기',()=>dropItem(id));itemMenu.querySelector('.cancel').onclick=()=>itemMenu.classList.add('hidden');itemMenu.classList.remove('hidden');}
function renderDroppedItem(d){let e=prop('droppedItem',d.x,d.y);e.dataset.uid=d.uid;e.innerHTML=`<img src="${items[d.id].img}" alt="${items[d.id].name}">`;return e;}
function renderDroppedItems(){(S.dropped[S.scene]||[]).forEach(renderDroppedItem);}
function nearbyDropped(r=55){return [...props.querySelectorAll('.droppedItem')].find(e=>nearElement(e,r));}
function pickupDropped(e){let list=S.dropped[S.scene]||[],i=list.findIndex(d=>d.uid===e.dataset.uid);if(i<0)return;let [d]=list.splice(i,1);if(!S.inv.includes(d.id))S.inv.push(d.id);e.remove();toast(`${items[d.id].name}을(를) 다시 주웠다.`);}
function dropItem(id){itemMenu.classList.add('hidden');if(S.scene==='world'){closeBag();toast('밖에서는 내려놓을 수 없습니다.',2100);return}if(!S.dropped[S.scene]){closeBag();toast('이곳에서는 내려놓을 수 없습니다.',2100);return}S.inv=S.inv.filter(v=>v!==id);let d={uid:`drop-${++S.dropSeq}`,id,x:Math.max(50,Math.min(950,S.x+(S.face==='right'?48:-48))),y:Math.max(105,Math.min(510,S.y+6))};S.dropped[S.scene].push(d);closeBag();renderDroppedItem(d);toast(`${items[id].name}을(를) 바닥에 내려놓았다.`);} 
function offerToElephant(id){closeBag();say([{who:'코끼리',t:'그건 네가 가장 소중히 생각하는 것이 아니야.'}]);}
function discard(id){if(id==='bag')return;S.inv=S.inv.filter(v=>v!==id);S.discarded.push(id);toast(`${items[id].name}을(를) 버렸다.`);renderBag();}
function renderDojo(){base('dojo','dojo',500,500);prop('banner',0,0);npc(A.child,510,220,10.5,S.q1.grown?'yellowbelt':'').id='child';let ps=[[120,155,-13],[220,245,8],[338,160,21],[680,165,-6],[850,260,15],[120,400,4],[255,445,-20],[390,345,12],[575,420,-10],[720,350,19],[875,440,-14],[520,292,5]];ps.forEach((p,i)=>{if(S.q1.pieces.has(i))return;let e=prop('shard',p[0],p[1]);e.dataset.i=i;e.style.setProperty('--r',p[2]+'deg')});renderDroppedItems();say([{who:'초여름',t:'안녕 꼬마야. 내가 어떤 남자애를 찾고 있는데 혹시 봤니?'},{who:'꼬마',t:'아니... 본 적 없어. 난 이 집에서 송판 깨기만 연마하느라 나가질 않았거든.'},{who:'꼬마',t:'그래서 말인데 이 산산조각난 송판 모으는 걸 좀 도와줄래?'}]);}
function q1Child(){if(S.q1.pieces.size<12){say([{who:'꼬마',t:'아직 조각이 남아 있어.'}]);return}if(!$('#wholeboard')){let b=prop('board',440,196);b.id='wholeboard'}let prompt=()=>say([{who:'꼬마',t:'다 모았다. 이제 이 송판을 꼭 깨야 해.'},{who:'',t:'송판을 어떻게 할까?',opts:[{label:'꼬마에게 돌려준다',go:()=>q1Fail(prompt)},{label:'바닥에 내려놓는다',go:q1Solve}]}]);prompt();}
function q1Fail(again){S.q1.attempts++;let b=$('#wholeboard');if(b)b.animate([{transform:'translateY(0)'},{transform:'translateY(90px) rotate(20deg)'},{transform:'translateY(0)'}],{duration:650,easing:'steps(4)'});say([{who:'꼬마',t:S.q1.attempts===1?'안 깨져… 왜 또 안 되는 거야?':'또 실패했어. 난 역시 안 되나 봐.'},{who:'꼬마',t:'다시 줘.'}],again);}
function q1Solve(){S.q1.grown=true;prop('grownbelt',510,203);say([{who:'초여름',t:'깨지 못해도 괜찮아.'},{who:'꼬마',t:'그럼… 오늘은 깨지 않아도 되는 거야?'},{who:'꼬마',t:'이건 누나가 가져.'},{who:'꼬마',t:'아 맞아. 그런데 듣기로 옆집 할머니께서 마을 안쪽 큰 성에 이상한 것이 산다고 얘기해주셨어.'},{who:'꼬마',t:'누나가 찾는 사람이 거기 있을지도 몰라.'}],()=>finishQuest(0,'belt','매듭진 흰띠를 받았다.'));}
function renderKitchen(){base('kitchen','kitchen',510,500);prop('sink',0,0);prop('table',0,0);let ch=prop('chair',0,0);ch.id='chair';npc(A.grandma,860,300,11.5).id='grandma';[[150,170],[220,225],[300,175]].forEach((p,i)=>{if(!S.q2.dishes.has(i)){let d=prop('dish',p[0],p[1]);d.dataset.i=i}});S.q2.placed.forEach(i=>placeDishVisual(i));renderDroppedItems();say([{who:'초여름',t:'안녕하세요. 혹시 어떤 남자애 못 보셨나요?'},{who:'할머니',t:'또 그때가 되었나보군. 여기엔 없어... 난 기다리는 사람이 있어서 이 집을 못 나간단다.'},{who:'초여름',t:'그때라는 게 무슨 의미죠?'},{who:'할머니',t:'흠... 아가씨 내 식사 준비를 좀 도와주지 않겠나? 그럼 그 의미를 알려주지...'}]);}
function placeDishVisual(i){let spots=[[570,245],[650,245],[735,245]],e=prop('tableDish',spots[i][0],spots[i][1]);e.dataset.i=i;}
function animateTo(x,y,dur=500){return new Promise(resolve=>{locked=true;let x0=S.x,y0=S.y,start=performance.now();function step(t){let p=Math.min(1,(t-start)/dur);S.x=x0+(x-x0)*p;S.y=y0+(y-y0)*p;if(x!==x0)S.face=x<x0?'left':'right';player.classList.add('walk');updatePlayer();if(p<1)requestAnimationFrame(step);else{player.classList.remove('walk');locked=false;resolve()}}requestAnimationFrame(step)});}
async function washDish(dish){let i=Number(dish.dataset.i),ox=S.x,oy=S.y;S.q2.dishes.add(i);dish.remove();toast(`식기를 씻었다. ${S.q2.dishes.size}/3`);await animateTo(620+i*45,315,650);S.q2.placed.add(i);placeDishVisual(i);await animateTo(ox,oy,550);}
function q2Sit(){if(S.q2.dishes.size<3){toast('의자는 아직 비어 있다.');return}say([{who:'할머니',t:'고맙구나... 사실 그 아이가 돌아오지 않은 지 이미 수십 년이 지났단다.'},{who:'할머니',t:'난 늘 오지 않은 아이를 위해 식사를 준비했어.'},{who:'초여름',t:'할머니. 더는 기다리지 마세요.'},{who:'초여름',t:'이런 모습을 보면 그 아이도 기뻐하지 않을 거예요.'},{who:'할머니',t:'때가 되면 이 마을엔 알 수 없는 재앙이 일어난단다. 그걸 막기 위해 누군가는 희생할 수밖에 없는 게야.'},{who:'할머니',t:'아가씨가 찾는 그 남자도 빨리 찾으러 가지 않으면 위험할 거야...'},{who:'할머니',t:'이게 도움이 될 거다.'}],()=>finishQuest(1,'bag','큰 가방을 받았다.'));}
function renderOffice(){base('office','office',510,500);prop('desk',0,0);npc(A.boss,780,300,12).id='boss';if(S.q3.stamp&&!S.q3.holdingStamp){let st=prop('stamp',410,290);st.id='stamp';st.style.pointerEvents='auto';st.onclick=()=>pickupStamp();}let t=prop('trash',820,430);t.id='officeTrash';papers();if(S.q3.holdingStamp)makeHeldStamp();renderDroppedItems();say([{who:'초여름',t:'혹시 어떤 남자애 보셨나요?'},{who:'부장님',t:'난 근무 중이야. 내가 언제 쉬었는지 기억도 안 나.'}]);}
function papers(){props.querySelectorAll('.paper').forEach(e=>e.remove());let ps=[[300,220,-9],[380,250,7],[460,225,3],[545,245,-4],[610,210,8],[330,315,-6],[420,325,11],[510,305,-2],[600,320,5],[285,370,-8],[385,380,9]];ps.slice(0,Math.min(ps.length,5+S.q3.papers)).forEach(p=>{let e=prop('paper',p[0],p[1]);e.style.setProperty('--r',p[2]+'deg')});}
function stampPaper(){if(S.q3.holdingStamp)return;S.q3.papers++;papers();if(S.q3.papers===2||S.q3.papers===4)toast('서류가 다시 쌓였다.');}
function pickupStamp(){if(S.q3.papers<3){toast('도장은 아직 책상 위에 놓여 있다.');return}S.q3.holdingStamp=true;let s=$('#stamp');if(s)s.remove();makeHeldStamp();toast('결재 도장을 들었다.');}
function makeHeldStamp(){let h=prop('heldStamp',S.x+25,S.y-32);h.id='heldStamp';}
function throwStamp(){if(!S.q3.holdingStamp)return;S.q3.holdingStamp=false;S.q3.stamp=false;let h=$('#heldStamp');if(h)h.remove();say([{who:'부장님',t:'내 이름이… 부장님이 아니었던 때가 있었지.'},{who:'부장님',t:'이 사진을 가져가.'}],()=>finishQuest(2,'photo','사진을 받았다.'));}
function renderMemory(){base('memory','memory',500,500);[['mem mem1',120,170],['mem mem1',260,380],['mem mem2',650,360],['mem mem2',760,160],['mem mem3',860,250],['mem mem3',390,145],['shard',180,300],['shard',720,455],['paper',310,425],['paper',590,190]].forEach((p,i)=>{let e=prop(p[0],p[1],p[2]);if(p[0].includes('shard'))e.style.setProperty('--r',(i*13)+'deg');if(p[0].includes('paper'))e.style.setProperty('--r',(i*7-10)+'deg')});prop('fog',0,0).id='fog';npc(A.elephant,500,300,15).id='elephant';renderDroppedItems();say([{who:'코끼리',t:'넌 이곳에 발을 들인 이상 맘대로 나갈 수 없어.'},{who:'코끼리',t:'너에게 가장 최고로 소중한 것을 나에게 넘기면 나갈 수 있게 해주지.'}],()=>{S.q4.intro=true});}
function elephantTalk(){say([{who:'코끼리',t:'너에게 가장 최고로 소중한 것을 나에게 넘기면 나갈 수 있게 해주지.'}]);}
function hug(){if(S.scene!=='memory'||S.q4.hugged||dist(S.x,S.y,500,300)>95||!dialogue.classList.contains('hidden'))return false;S.q4.hugged=true;locked=true;S.x=500;S.y=365;updatePlayer();player.classList.add('hugging');let el=$('#elephant');if(el)el.classList.add('beingHugged');bg.classList.add('bright');props.querySelectorAll('.mem,.fog,.paper,.shard').forEach(e=>e.classList.add('fade'));prop('heart',500,160,'♥');setTimeout(()=>{locked=false;say([{who:'코끼리',t:'날 껴안아준 거야?'},{who:'코끼리',t:'너에게 가장 소중한 건 이런 거구나... 마음이 따뜻해져.'},{who:'코끼리',t:'이건 네가 가져가.'}],()=>{player.classList.remove('hugging');finishQuest(3,'coin','코인을 받았다.')})},420);return true;}
function finishQuest(i,item,msg){S.complete[i]=true;if(!S.inv.includes(item))S.inv.push(item);toast(msg,1500);setTimeout(()=>sceneTransition(()=>{S.x=doors[i].x;S.y=doors[i].y+65;renderWorld()}),650);}
function renderCastle(){base('castle','castle',500,500);prop('floor',0,0);npc(A.boy,555,335,11).id='boy';renderDroppedItems();if(S.q5.attempts)bg.classList.add('s'+Math.min(3,S.q5.attempts));say([{who:'박이상',t:'나를 찾아냈구나.'},{who:'초여름',t:'너 무사한 거야?'},{who:'박이상',t:'응 보다시피.'},{who:'초여름',t:'근데 왜 탈출하려 하지 않은 거야?'},{who:'박이상',t:'모르겠어. 근데 나 여기서 나가고 싶지가 않아.'},{who:'박이상',t:'이상하게 발이 안 움직이네. 날 좀 도와줄래?'}]);}
function castleTalk(){let onlyBag=S.inv.length===1&&S.inv[0]==='bag';say([{who:'',t:'어떻게 할까?',opts:[{label:'가지고 온 물건을 건넨다',go:castleOffer},{label:'가방을 바닥에 내려놓는다',go:()=>onlyBag?castleSuccess():say([{who:'박이상',t:'……'}])}]}]);}
function castleOffer(){if(!S.inv.length){say([{who:'초여름',t:'건넬 물건이 없다.'}]);return}let id=S.inv.find(v=>v!=='bag')||S.inv[0];S.inv.splice(S.inv.indexOf(id),1);S.q5.attempts++;locked=true;bg.classList.add('shake','s'+Math.min(3,S.q5.attempts));setTimeout(()=>{bg.classList.remove('shake');locked=false;if(S.q5.attempts>=3){flash.className='flashing';setTimeout(()=>{flash.className='hidden';ending.className='failure';ending.querySelector('p').textContent='난 이곳을 벗어나지 못할 거야…';$('#again').textContent='다시 시도하기';ending.classList.remove('hidden')},2300)}else{say([{who:'박이상',t:'……'}])}},700);}
function castleSuccess(){locked=true;let floorBag=prop('floorbag',465,390);floorBag.style.background=`url('${A.bag}') center/contain no-repeat`;let boy=$('#boy');if(boy)boy.classList.add('enterbag');say([{who:'박이상',t:'……'}],()=>{S.inv=['bag_man'];S.bagHasMan=true;S.finalRun=true;S.x=820;S.y=300;renderWorld();startAutoRun()});}
function startAutoRun(){locked=true;carry.classList.remove('hidden');let target={x:500,y:505},start=performance.now(),dur=3400,x0=S.x,y0=S.y;function step(t){let p=Math.min(1,(t-start)/dur),ease=1-Math.pow(1-p,2);S.x=x0+(target.x-x0)*ease;S.y=y0+(target.y-y0)*ease;S.face=S.x<x0?'left':'right';player.classList.add('walk');updatePlayer();if(p<1)requestAnimationFrame(step);else{player.classList.remove('walk');locked=false;say([{who:'초여름',t:'어째서 나갈 수가 없는 거지?'},{who:'초여름',t:'더 이상 달려지지가 않아…'}])}}requestAnimationFrame(step);}
function repeatStuck(){say([{who:'초여름',t:'어째서 나갈 수가 없는 거지?'},{who:'초여름',t:'더 이상 달려지지가 않아…'}]);}
function finalDrop(){closeBag();locked=true;carry.classList.add('hidden');S.inv=[];let boy=npc(A.boy,S.x+65,S.y+4,6.2);boy.style.zIndex=8;boy.style.transform='translate(-50%,-87%)';say([{who:'박이상',t:'네가 날 꼭 붙잡고 있지 않아도, 난 네 곁에 있을 거야.'},{who:'박이상',t:'나에게 사랑을 알려줘서 고마워.'}],()=>setTimeout(()=>{ending.className='';ending.querySelector('p').textContent='THE END';$('#again').textContent='게임 다시하기'},350));}
function interact(){if(!started||locked)return;if(!dialogue.classList.contains('hidden')){advance();return}if(!bag.classList.contains('hidden'))return;if(S.finalRun&&S.scene==='world'){repeatStuck();return}if(S.scene!=='world'){let dropped=nearbyDropped();if(dropped){pickupDropped(dropped);return}}if(S.scene==='world'){let d=doors.find(v=>dist(S.x,S.y,v.x,v.y)<68);if(d)enter(d);return}if(S.scene==='dojo'){let shard=[...props.querySelectorAll('.shard')].find(e=>nearElement(e,45));if(shard){S.q1.pieces.add(Number(shard.dataset.i));shard.remove();toast(`송판 조각 ${S.q1.pieces.size}/12`);return}if(dist(S.x,S.y,510,220)<85)q1Child();return}if(S.scene==='kitchen'){let dish=[...props.querySelectorAll('.dish')].find(e=>nearElement(e,48));if(dish){washDish(dish);return}if(S.q2.dishes.size===3&&dist(S.x,S.y,860,300)<92){say([{who:'할머니',t:'언제 오려나.....'}]);return}if(dist(S.x,S.y,660,392)<75)q2Sit();return}if(S.scene==='office'){if(S.q3.holdingStamp&&dist(S.x,S.y,820,430)<75){throwStamp();return}if(!S.q3.holdingStamp&&dist(S.x,S.y,410,290)<65){pickupStamp();return}if(dist(S.x,S.y,420,280)<125){stampPaper();return}}if(S.scene==='memory'&&dist(S.x,S.y,500,300)<95)elephantTalk();if(S.scene==='castle'&&dist(S.x,S.y,555,335)<95)castleTalk();}
function pocket(){if(!started||locked||!dialogue.classList.contains('hidden'))return;if(!bag.classList.contains('hidden')){closeBag();return}openBag('view');}
function nearElement(e,r){return dist(S.x,S.y,parseFloat(e.style.left)/100*W,parseFloat(e.style.top)/100*H)<r}
function dist(x1,y1,x2,y2){return Math.hypot(x1-x2,y1-y2)}
function updatePlayer(){player.style.left=S.x/W*100+'%';player.style.top=S.y/H*100+'%';shadow.style.left=S.x/W*100+'%';shadow.style.top=(S.y+7)/H*100+'%';carry.style.left=S.x/W*100+'%';carry.style.top=S.y/H*100+'%';player.classList.toggle('right',S.face==='right');let h=$('#heldStamp');if(h){h.style.left=(S.x+28)/W*100+'%';h.style.top=(S.y-28)/H*100+'%'}}
function updateHint(){if(!started||locked||!dialogue.classList.contains('hidden')||!bag.classList.contains('hidden')){hint.classList.add('hidden');return}let msg='';if(S.scene!=='world'&&nearbyDropped())msg='A 줍기';else if(S.scene==='world'){if(S.finalRun)msg='A';else{let d=doors.find(v=>dist(S.x,S.y,v.x,v.y)<70);if(d)msg=unlocked(d.id)?'A 들어가기':'잠겨 있음'}}else if(S.scene==='dojo'){if([...props.querySelectorAll('.shard')].some(e=>nearElement(e,48)))msg='A 줍기';else if(dist(S.x,S.y,510,220)<90)msg='A 대화하기'}else if(S.scene==='kitchen'){if([...props.querySelectorAll('.dish')].some(e=>nearElement(e,50)))msg='A 씻기';else if(S.q2.dishes.size===3&&dist(S.x,S.y,860,300)<96)msg='A 대화하기';else if(S.q2.dishes.size===3&&dist(S.x,S.y,660,392)<80)msg='A 앉기'}else if(S.scene==='office'){if(S.q3.holdingStamp&&dist(S.x,S.y,820,430)<75)msg='A';else if(!S.q3.holdingStamp&&dist(S.x,S.y,410,290)<65&&S.q3.papers>=3)msg='A 집기';else if(dist(S.x,S.y,420,280)<120&&!S.q3.holdingStamp)msg='A 결재하기'}else if(S.scene==='memory'&&dist(S.x,S.y,500,300)<100)msg='A 대화하기';else if(S.scene==='castle'&&dist(S.x,S.y,555,335)<100)msg='A 대화하기';hint.textContent=msg;hint.classList.toggle('hidden',!msg);}
function loop(t){let dt=Math.min(.035,(t-last)/1000);last=t;if(started&&!locked&&dialogue.classList.contains('hidden')&&bag.classList.contains('hidden')){let dx=(keys.right?1:0)-(keys.left?1:0),dy=(keys.down?1:0)-(keys.up?1:0);if(dx||dy){let len=Math.hypot(dx,dy),speed=S.scene==='world'?190:170;S.x+=dx/len*speed*dt;S.y+=dy/len*speed*dt;S.x=Math.max(35,Math.min(965,S.x));S.y=Math.max(90,Math.min(525,S.y));if(dx<0)S.face='left';if(dx>0)S.face='right';player.classList.add('walk')}else player.classList.remove('walk');updatePlayer();updateHint()}requestAnimationFrame(loop);}
function keyDir(k,v){let map={ArrowUp:'up',w:'up',W:'up',ArrowDown:'down',s:'down',S:'down',ArrowLeft:'left',j:'left',J:'left',ArrowRight:'right',d:'right',D:'right'};if(map[k]){keys[map[k]]=v;return true}return false;}
function pressAction(key){keys[key]=true;$('#'+key+'Btn').classList.add('down');if(keys.a&&keys.b){clearTimeout(comboTimer);comboTimer=null;if(hug())return}let fn=key==='a'?interact:pocket;if(S.scene==='memory'&&dist(S.x,S.y,500,300)<105)comboTimer=setTimeout(()=>{if(keys[key]&&!(keys.a&&keys.b))fn()},120);else fn();}
function releaseAction(key){keys[key]=false;$('#'+key+'Btn').classList.remove('down');}
function actionFromEvent(e){if(e.code==='KeyA'||e.key==='a'||e.key==='A'||e.key==='ㅁ')return 'a';if(e.code==='KeyB'||e.key==='b'||e.key==='B'||e.key==='ㅠ')return 'b';return '';}
function onKeyDown(e){ensureBgm();if(!dialogue.classList.contains('hidden')&&['ArrowUp','ArrowDown'].includes(e.key)){moveChoice(e.key==='ArrowUp'?-1:1);e.preventDefault();return}if(keyDir(e.key,true)){e.preventDefault();return}let action=actionFromEvent(e);if(action){e.preventDefault();e.stopPropagation();if(!e.repeat&&!keys[action])pressAction(action);return}if(e.code==='Space'||e.key===' '){if(!dialogue.classList.contains('hidden'))advance();else interact();e.preventDefault();}}
function onKeyUp(e){keyDir(e.key,false);let action=actionFromEvent(e);if(action){e.preventDefault();releaseAction(action);}}
document.addEventListener('contextmenu',e=>e.preventDefault());
document.addEventListener('touchmove',e=>{if(e.target.closest('#bag'))return;if(e.target.closest('#game'))e.preventDefault()},{passive:false});
document.addEventListener('keydown',onKeyDown,true);document.addEventListener('keyup',onKeyUp,true);window.addEventListener('blur',()=>{['a','b'].forEach(releaseAction);['up','down','left','right'].forEach(k=>keys[k]=false)});
dialogue.addEventListener('click',e=>{ensureBgm();if(e.target.closest('.choice'))return;advance()});
function bindHold(el,on,off){if(window.PointerEvent){el.addEventListener('pointerdown',e=>{ensureBgm();e.preventDefault();el.setPointerCapture?.(e.pointerId);on(e)},{passive:false});['pointerup','pointercancel','pointerleave'].forEach(ev=>el.addEventListener(ev,e=>{e.preventDefault();off(e)},{passive:false}))}else{el.addEventListener('touchstart',e=>{ensureBgm();e.preventDefault();on(e)},{passive:false});['touchend','touchcancel'].forEach(ev=>el.addEventListener(ev,e=>{e.preventDefault();off(e)},{passive:false}));el.addEventListener('mousedown',e=>{ensureBgm();e.preventDefault();on(e)});['mouseup','mouseleave'].forEach(ev=>el.addEventListener(ev,e=>{e.preventDefault();off(e)}))}}
[...document.querySelectorAll('#dpad button')].forEach(b=>{let d=b.dataset.dir;bindHold(b,()=>keys[d]=true,()=>keys[d]=false)});
function bindAction(el,key){bindHold(el,()=>{if(!keys[key])pressAction(key)},()=>releaseAction(key));}
bindAction($('#aBtn'),'a');bindAction($('#bBtn'),'b');$('#bagClose').onclick=()=>closeBag();$('#introNext').onclick=()=>{ensureBgm();$('#intro').classList.add('hidden');$('#title').classList.remove('hidden')};$('#start').onclick=()=>{ensureBgm();started=true;$('#title').classList.add('hidden');say([{who:'초여름',t:'이상이를 찾아야 해.'},{who:'초여름',t:'저 성 안에 갇힌 게 분명해.'}])};$('#reset').onclick=()=>{ensureBgm();reset(true)};$('#again').onclick=()=>{ensureBgm();reset(true)};bgm?.addEventListener('ended',()=>{bgm.currentTime=0;ensureBgm()});ensureBgm();requestAnimationFrame(loop);reset(true);
})();
